-- AGRO MIRAI storage schema (v1) — postgres
-- GENERATED by tools/gen_migrations.py from specs/core/schema.yaml.
-- Do not hand-edit; change schema.yaml and regenerate.


CREATE TABLE IF NOT EXISTS "farmers" (
  "id" uuid NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "name" text NOT NULL,
  "preferred_language" text NOT NULL,
  "phone" text,
  "district" text,
  "state" text,
  "email" text,
  "password_hash" text,
  "role" text,
  "photo_url" text,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "fields" (
  "id" uuid NOT NULL,
  "farmer_id" uuid NOT NULL REFERENCES "farmers"("id") ON DELETE CASCADE,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "name" text NOT NULL,
  "latitude" double precision NOT NULL,
  "longitude" double precision NOT NULL,
  "area_ha" double precision NOT NULL,
  "elevation_m" double precision,
  "soil_type" text,
  "current_crop" text,
  "sown_on" date,
  PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_fields_farmer_id" ON "fields"("farmer_id");

CREATE TABLE IF NOT EXISTS "weather_readings" (
  "id" uuid NOT NULL,
  "field_id" uuid NOT NULL REFERENCES "fields"("id") ON DELETE CASCADE,
  "observed_at" timestamptz NOT NULL,
  "source" text NOT NULL,
  "temp_c" double precision NOT NULL,
  "temp_min_c" double precision,
  "temp_max_c" double precision,
  "humidity_pct" double precision,
  "rainfall_mm" double precision,
  "wind_mps" double precision,
  "is_forecast" boolean NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_weather_readings_field_id" ON "weather_readings"("field_id");

CREATE TABLE IF NOT EXISTS "soil_samples" (
  "id" uuid NOT NULL,
  "field_id" uuid NOT NULL REFERENCES "fields"("id") ON DELETE CASCADE,
  "observed_at" timestamptz NOT NULL,
  "source" text NOT NULL,
  "ph" double precision,
  "nitrogen_mg_per_kg" double precision,
  "phosphorus_mg_per_kg" double precision,
  "potassium_mg_per_kg" double precision,
  "organic_carbon_pct" double precision,
  "moisture_pct" double precision,
  PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_soil_samples_field_id" ON "soil_samples"("field_id");

CREATE TABLE IF NOT EXISTS "ndvi_readings" (
  "id" uuid NOT NULL,
  "field_id" uuid NOT NULL REFERENCES "fields"("id") ON DELETE CASCADE,
  "observed_at" timestamptz NOT NULL,
  "source" text NOT NULL,
  "ndvi" double precision NOT NULL,
  "cloud_cover_pct" double precision,
  "satellite" text,
  PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_ndvi_readings_field_id" ON "ndvi_readings"("field_id");

CREATE TABLE IF NOT EXISTS "crop_recommendations" (
  "id" uuid NOT NULL,
  "field_id" uuid NOT NULL REFERENCES "fields"("id") ON DELETE CASCADE,
  "created_at" timestamptz NOT NULL,
  "recommended_crop" text NOT NULL,
  "confidence" double precision NOT NULL,
  "alternatives" jsonb,
  "rationale" text,
  "season" text,
  "out_of_region" boolean,
  "regional_alternative" text,
  PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_crop_recommendations_field_id" ON "crop_recommendations"("field_id");

CREATE TABLE IF NOT EXISTS "irrigation_advices" (
  "id" uuid NOT NULL,
  "field_id" uuid NOT NULL REFERENCES "fields"("id") ON DELETE CASCADE,
  "created_at" timestamptz NOT NULL,
  "recommended_depth_mm" double precision NOT NULL,
  "window_start_at" timestamptz NOT NULL,
  "window_end_at" timestamptz NOT NULL,
  "urgency" text NOT NULL,
  "rationale" text,
  PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_irrigation_advices_field_id" ON "irrigation_advices"("field_id");

CREATE TABLE IF NOT EXISTS "disease_risk_alerts" (
  "id" uuid NOT NULL,
  "field_id" uuid NOT NULL REFERENCES "fields"("id") ON DELETE CASCADE,
  "created_at" timestamptz NOT NULL,
  "disease" text NOT NULL,
  "risk_level" text NOT NULL,
  "confidence" double precision NOT NULL,
  "window_start_at" timestamptz,
  "window_end_at" timestamptz,
  "recommended_action" text,
  "source" text,
  PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_disease_risk_alerts_field_id" ON "disease_risk_alerts"("field_id");

CREATE TABLE IF NOT EXISTS "advisories" (
  "id" uuid NOT NULL,
  "field_id" uuid NOT NULL REFERENCES "fields"("id") ON DELETE CASCADE,
  "created_at" timestamptz NOT NULL,
  "language" text NOT NULL,
  "title" text NOT NULL,
  "body" text NOT NULL,
  "severity" text NOT NULL,
  "source_refs" jsonb,
  PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_advisories_field_id" ON "advisories"("field_id");

CREATE TABLE IF NOT EXISTS "feedback_entries" (
  "id" uuid NOT NULL,
  "farmer_id" uuid NOT NULL REFERENCES "farmers"("id") ON DELETE CASCADE,
  "advisory_id" uuid NOT NULL REFERENCES "advisories"("id") ON DELETE CASCADE,
  "created_at" timestamptz NOT NULL,
  "rating" integer NOT NULL,
  "helpful" boolean NOT NULL,
  "comment" text,
  PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_feedback_entries_farmer_id" ON "feedback_entries"("farmer_id");
CREATE INDEX IF NOT EXISTS "idx_feedback_entries_advisory_id" ON "feedback_entries"("advisory_id");
