"""Builds src/pickImages.ts from whatever soil_*/crop_* images exist in assets/pick/.
Metro needs static require() calls, so the list is generated. Re-run after adding images:
    python scripts/gen_pick_index.py
Missing images simply fall back to a tinted icon tile in the app."""
import pathlib, re

root = pathlib.Path(__file__).resolve().parent.parent
pick = root / 'assets' / 'pick'
files = sorted(p for p in pick.iterdir() if re.match(r'^(soil|crop)_[a-z]+\.(png|jpe?g|webp)$', p.name))
lines = [
    '// GENERATED by scripts/gen_pick_index.py -- do not edit by hand.',
    'export const PICK_IMAGES: Record<string, number> = {',
]
for p in files:
    lines.append(f"  {p.stem}: require('../assets/pick/{p.name}'),")
lines.append('};')
(root / 'src' / 'pickImages.ts').write_text('\n'.join(lines) + '\n', encoding='utf8')
print(f'{len(files)} images indexed')
