#!/usr/bin/env python3
"""Generate SQLite and Postgres DDL from ``specs/core/schema.yaml``.

Why generated, not hand-written: ``schema.yaml`` is already a structured,
machine-readable description of every entity/field/type/ref (the same
document ``tools/check_specs.py`` parses to validate the golden fixture).
Hand-writing two DDL dialects field-by-field against a 10-entity, ~90
field schema is exactly the kind of divergence-prone busywork a small
generator removes — a field added to schema.yaml regenerates both
dialects instead of risking SQLite/Postgres/schema drift. See
``decisions/0005-migration-generation.md``.

Usage:

    python tools/gen_migrations.py

Writes ``migrations/sqlite/001_init.sql`` and
``migrations/postgres/001_init.sql``. Deterministic — table/column order
follows schema.yaml's entity/field order, safe to diff and re-run.
"""
from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SCHEMA_PATH = ROOT / "specs" / "core" / "schema.yaml"
SQLITE_OUT = ROOT / "migrations" / "sqlite" / "001_init.sql"
POSTGRES_OUT = ROOT / "migrations" / "postgres" / "001_init.sql"

# Entity name -> table name (matches tools/check_specs.py's
# FIXTURE_COLLECTION_TO_ENTITY, just inverted).
TABLE_NAMES = {
    "Farmer": "farmers",
    "Field": "fields",
    "WeatherReading": "weather_readings",
    "SoilSample": "soil_samples",
    "NDVIReading": "ndvi_readings",
    "CropRecommendation": "crop_recommendations",
    "IrrigationAdvice": "irrigation_advices",
    "DiseaseRiskAlert": "disease_risk_alerts",
    "Advisory": "advisories",
    "FeedbackEntry": "feedback_entries",
}

# Entities in FK-safe creation order (parents before children).
ENTITY_ORDER = [
    "Farmer",
    "Field",
    "WeatherReading",
    "SoilSample",
    "NDVIReading",
    "CropRecommendation",
    "IrrigationAdvice",
    "DiseaseRiskAlert",
    "Advisory",
    "FeedbackEntry",
]

SQLITE_TYPES = {
    "uuid": "TEXT",
    "timestamp": "TEXT",
    "date": "TEXT",
    "string": "TEXT",
    "int": "INTEGER",
    "float": "REAL",
    "bool": "INTEGER",
    "list": "TEXT",
}

POSTGRES_TYPES = {
    "uuid": "uuid",
    "timestamp": "timestamptz",
    "date": "date",
    "string": "text",
    "int": "integer",
    "float": "double precision",
    "bool": "boolean",
    "list": "jsonb",
}


def load_schema() -> dict:
    return yaml.safe_load(SCHEMA_PATH.read_text(encoding="utf-8"))


def gen_column(fname: str, fspec: dict, types: dict, dialect: str) -> str:
    col_type = types[fspec["type"]]
    parts = [f'"{fname}"', col_type]
    if fspec.get("required"):
        parts.append("NOT NULL")
    ref = fspec.get("ref")
    if ref:
        target_entity, target_field = ref.split(".")
        target_table = TABLE_NAMES[target_entity]
        parts.append(f'REFERENCES "{target_table}"("{target_field}") ON DELETE CASCADE')
    return " ".join(parts)


def gen_table(entity_name: str, espec: dict, types: dict, dialect: str) -> str:
    table = TABLE_NAMES[entity_name]
    fields = espec["fields"]
    lines = [f'CREATE TABLE IF NOT EXISTS "{table}" (']
    col_lines = [f"  {gen_column(fname, fspec, types, dialect)}" for fname, fspec in fields.items()]
    col_lines.append('  PRIMARY KEY ("id")')
    lines.append(",\n".join(col_lines))
    lines.append(");")
    return "\n".join(lines)


def gen_indexes(entity_name: str, espec: dict, dialect: str) -> list[str]:
    table = TABLE_NAMES[entity_name]
    fields = espec["fields"]
    stmts = []
    for fname, fspec in fields.items():
        if fspec.get("ref") and fname != "id":
            idx = f"idx_{table}_{fname}"
            stmts.append(f'CREATE INDEX IF NOT EXISTS "{idx}" ON "{table}"("{fname}");')
    return stmts


def build_ddl(schema: dict, types: dict, dialect: str) -> str:
    entities = schema["entities"]
    header = (
        f"-- AGRO MIRAI storage schema ({schema['version']}) — {dialect}\n"
        "-- GENERATED by tools/gen_migrations.py from specs/core/schema.yaml.\n"
        "-- Do not hand-edit; change schema.yaml and regenerate.\n\n"
    )
    parts = [header]
    for entity_name in ENTITY_ORDER:
        espec = entities[entity_name]
        parts.append(gen_table(entity_name, espec, types, dialect))
        parts.append("")
        idx = gen_indexes(entity_name, espec, dialect)
        if idx:
            parts.extend(idx)
            parts.append("")
    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    schema = load_schema()
    SQLITE_OUT.parent.mkdir(parents=True, exist_ok=True)
    POSTGRES_OUT.parent.mkdir(parents=True, exist_ok=True)
    SQLITE_OUT.write_text(build_ddl(schema, SQLITE_TYPES, "sqlite"), encoding="utf-8")
    POSTGRES_OUT.write_text(build_ddl(schema, POSTGRES_TYPES, "postgres"), encoding="utf-8")
    print(f"wrote {SQLITE_OUT.relative_to(ROOT)}")
    print(f"wrote {POSTGRES_OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
