-- AGRO MIRAI storage schema (v1) — sqlite
-- GENERATED by tools/gen_migrations.py from specs/core/schema.yaml.
-- Do not hand-edit; change schema.yaml and regenerate.


CREATE TABLE IF NOT EXISTS "farmers" (
  "id" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "preferred_language" TEXT NOT NULL,
  "phone" TEXT,
  "district" TEXT,
  "state" TEXT,
  "email" TEXT,
  "password_hash" TEXT,
  "role" TEXT,
  "photo_url" TEXT,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "fields" (
  "id" TEXT NOT NULL,
  "farmer_id" TEXT NOT NULL REFERENCES "farmers"("id") ON DELETE CASCADE,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "latitude" REAL NOT NULL,
  "longitude" REAL NOT NULL,
  "area_ha" REAL NOT NULL,
  "elevation_m" REAL,
  "soil_type" TEXT,
  "current_crop" TEXT,
  "sown_on" TEXT,
  PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_fields_farmer_id" ON "fields"("farmer_id");

CREATE TABLE IF NOT EXISTS "weather_readings" (
  "id" TEXT NOT NULL,
  "field_id" TEXT NOT NULL REFERENCES "fields"("id") ON DELETE CASCADE,
  "observed_at" TEXT NOT NULL,
  "source" TEXT NOT NULL,
  "temp_c" REAL NOT NULL,
  "temp_min_c" REAL,
  "temp_max_c" REAL,
  "humidity_pct" REAL,
  "rainfall_mm" REAL,
  "wind_mps" REAL,
  "is_forecast" INTEGER NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_weather_readings_field_id" ON "weather_readings"("field_id");

CREATE TABLE IF NOT EXISTS "soil_samples" (
  "id" TEXT NOT NULL,
  "field_id" TEXT NOT NULL REFERENCES "fields"("id") ON DELETE CASCADE,
  "observed_at" TEXT NOT NULL,
  "source" TEXT NOT NULL,
  "ph" REAL,
  "nitrogen_mg_per_kg" REAL,
  "phosphorus_mg_per_kg" REAL,
  "potassium_mg_per_kg" REAL,
  "organic_carbon_pct" REAL,
  "moisture_pct" REAL,
  PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_soil_samples_field_id" ON "soil_samples"("field_id");

CREATE TABLE IF NOT EXISTS "ndvi_readings" (
  "id" TEXT NOT NULL,
  "field_id" TEXT NOT NULL REFERENCES "fields"("id") ON DELETE CASCADE,
  "observed_at" TEXT NOT NULL,
  "source" TEXT NOT NULL,
  "ndvi" REAL NOT NULL,
  "cloud_cover_pct" REAL,
  "satellite" TEXT,
  PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_ndvi_readings_field_id" ON "ndvi_readings"("field_id");

CREATE TABLE IF NOT EXISTS "crop_recommendations" (
  "id" TEXT NOT NULL,
  "field_id" TEXT NOT NULL REFERENCES "fields"("id") ON DELETE CASCADE,
  "created_at" TEXT NOT NULL,
  "recommended_crop" TEXT NOT NULL,
  "confidence" REAL NOT NULL,
  "alternatives" TEXT,
  "rationale" TEXT,
  "season" TEXT,
  "out_of_region" INTEGER,
  "regional_alternative" TEXT,
  PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_crop_recommendations_field_id" ON "crop_recommendations"("field_id");

CREATE TABLE IF NOT EXISTS "irrigation_advices" (
  "id" TEXT NOT NULL,
  "field_id" TEXT NOT NULL REFERENCES "fields"("id") ON DELETE CASCADE,
  "created_at" TEXT NOT NULL,
  "recommended_depth_mm" REAL NOT NULL,
  "window_start_at" TEXT NOT NULL,
  "window_end_at" TEXT NOT NULL,
  "urgency" TEXT NOT NULL,
  "rationale" TEXT,
  PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_irrigation_advices_field_id" ON "irrigation_advices"("field_id");

CREATE TABLE IF NOT EXISTS "disease_risk_alerts" (
  "id" TEXT NOT NULL,
  "field_id" TEXT NOT NULL REFERENCES "fields"("id") ON DELETE CASCADE,
  "created_at" TEXT NOT NULL,
  "disease" TEXT NOT NULL,
  "risk_level" TEXT NOT NULL,
  "confidence" REAL NOT NULL,
  "window_start_at" TEXT,
  "window_end_at" TEXT,
  "recommended_action" TEXT,
  "source" TEXT,
  PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_disease_risk_alerts_field_id" ON "disease_risk_alerts"("field_id");

CREATE TABLE IF NOT EXISTS "advisories" (
  "id" TEXT NOT NULL,
  "field_id" TEXT NOT NULL REFERENCES "fields"("id") ON DELETE CASCADE,
  "created_at" TEXT NOT NULL,
  "language" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "body" TEXT NOT NULL,
  "severity" TEXT NOT NULL,
  "source_refs" TEXT,
  PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_advisories_field_id" ON "advisories"("field_id");

CREATE TABLE IF NOT EXISTS "feedback_entries" (
  "id" TEXT NOT NULL,
  "farmer_id" TEXT NOT NULL REFERENCES "farmers"("id") ON DELETE CASCADE,
  "advisory_id" TEXT NOT NULL REFERENCES "advisories"("id") ON DELETE CASCADE,
  "created_at" TEXT NOT NULL,
  "rating" INTEGER NOT NULL,
  "helpful" INTEGER NOT NULL,
  "comment" TEXT,
  PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "idx_feedback_entries_farmer_id" ON "feedback_entries"("farmer_id");
CREATE INDEX IF NOT EXISTS "idx_feedback_entries_advisory_id" ON "feedback_entries"("advisory_id");
